#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement

test ! -n "${1}" && printf "usage: ${0} <commit-message>\n" && exit 1
commit_message="$1"

hugo

deploy_folder="$HOME/prog/personal/ryan-mcclue.github.io"
find "$deploy_folder"/ -not \( -path "$deploy_folder/.git" -prune \) \
  -and -not \( -type d -wholename "$deploy_folder/" \) | xargs rm -rf 

cp -a public/. "$deploy_folder/"
cd "$deploy_folder"
git add . && git commit -m "$commit_message" --no-verify && git push origin master
cd -
