#!/bin/bash

set -e

markdown_files=$(find ~+ -type f \( -name "*.md" -not -name "README.md" -not -name "notes.md" \) -exec ls -tr {} +)

printf "$markdown_files" | xargs pandoc --pdf-engine=xelatex --toc -o musings.pdf

xdg-open ./musings.pdf
