#!/bin/sh

set -e

markdown_files=$(find ~+ -type f \( -name "*.md" -not -name "README.md" \) -exec ls -tr {} +)

printf "$markdown_files" | xargs \
  pandoc -s --metadata title="Musings" --toc \
    -f markdown -t html -o musings.html
